### ISSUE TITLE
Bug#2 - Login Page

### ISSUE THREAD

**Issue by RafCodez** [IndionicHost/Bug-report#2]
### Issue occurs on,

Windows 10/11

### Which panel/page has this issue?

Server panel

### Description

If you enable 2FA you can't login into panel
Reproduction Steps: Enable 2FA on your account. Then clear your browser cache after that try to login with same account and 2FA or backup code.
Attachments: 
![Bug](https://cdn.discordapp.com/attachments/1016240120019558450/1016242171009052682/unknown.png)

### Expected behavior

Try to login

### Actual behavior

2FA doesn't work

### Steps to reproduce this bug/error

Enable 2FA

### Path/location to problematic page

null

### Agreement

- [X] I have checked for and confirmed there isn't already a similar issue opened.
- [X] I have checked for and confirmed there isn't any browser addon/extension causing this issue.
- [X] I have tested and confirmed the presense of this bug on latest version of my preferred browser application.

**Comment by Anas-1554** [comment]
Fixed
