### ISSUE TITLE
Bug#3

### ISSUE THREAD

**Issue by NotRafey** [IndionicHost/Bug-report#3]
### Issue occurs on,

Windows 10/11

### Which panel/page has this issue?

Exotic server panel

### Description

You can't do anything in backup page.
Attachments: (Given below)
![images](https://cdn.discordapp.com/attachments/1016240120019558450/1016243105470619738/unknown.png)

### Expected behavior

 Make a server backup and try to do anything.

### Actual behavior

Wont work 

### Steps to reproduce this bug/error

Reproduction Steps: Make a server backup and try to do anything.

### Possible fix

Get Good

### Path/location to problematic page

null

### Agreement

- [X] I have checked for and confirmed there isn't already a similar issue opened.
- [X] I have checked for and confirmed there isn't any browser addon/extension causing this issue.
- [x] I have tested and confirmed the presense of this bug on latest version of my preferred browser application.

**Comment by kartikay-agarwal** [comment]
Fixed
