### ISSUE TITLE
Bug#4

### ISSUE THREAD

**Issue by RafCodez** [IndionicHost/Bug-report#4]
### Issue occurs on,

Windows 10/11

### Which panel/page has this issue?

Exotic server panel

### Description

Null link in side panel.

Attachments: (Given below) 
![w](https://cdn.discordapp.com/attachments/1016240120019558450/1016245797383327824/unknown.png)

### Expected behavior

Null man

### Actual behavior

Idk

### Steps to reproduce this bug/error

Reproduction Steps: Click on some links in side panel.

### Possible fix

Get good

### Path/location to problematic page

Why?

### Agreement

- [X] I have checked for and confirmed there isn't already a similar issue opened.
- [X] I have checked for and confirmed there isn't any browser addon/extension causing this issue.
- [X] I have tested and confirmed the presense of this bug on latest version of my preferred browser application.

**Comment by Anas-1554** [comment]
Fixed
