### ISSUE TITLE
.zip file Doesn't unarchive properly 

### ISSUE THREAD

**Issue by RafCodez** [IndionicHost/Bug-report#5]
### Issue occurs on,

Mobile

### Which panel/page has this issue?

Exotic server panel

### Description

When You Upload any file which is .zip and try to unarchive it doesn't work as it should. It wont unarchive folders instead it will paste all files inside zip without folder

### Expected behavior

Download any code as zip from github. Then try unzipping it you will notice files only not folders

### Actual behavior

I mentioned earlier 

### Steps to reproduce this bug/error

Download any code as zip from github. Then try unzipping it you will notice files only not folders

### Possible fix

Idk

### Path/location to problematic page

https://indionicpanel.in/server/8b496d29/files#/NewFolder

### Agreement

- [X] I have checked for and confirmed there isn't already a similar issue opened.
- [X] I have checked for and confirmed there isn't any browser addon/extension causing this issue.
- [X] I have tested and confirmed the presense of this bug on latest version of my preferred browser application.

**Comment by Anas-1554** [comment]
Fixed on main panel
