### ISSUE TITLE
Backups dont work once you locked them

### ISSUE THREAD

**Issue by KyleTheDev** [IndionicHost/Bug-report#6]
### Issue occurs on,

Desktop, Tablet, Mobile, Windows 10/11

### Which panel/page has this issue?

Server panel

### Description

If you make a backup and select the "locked" backup option, It wont let you unlock or delete It, simple would throw this error
![image](https://user-images.githubusercontent.com/75298673/208281372-fe6608a6-6df5-41f9-ad0f-b57fbc80da57.png)

Console log:
![image](https://user-images.githubusercontent.com/75298673/208281388-9bdbe4cd-d7fe-4b37-8075-2cd9a36fd753.png)

If any admin can unlock my backups or delete them please go ahead, https://indionicpanel.in/server/ed62fd04

### Expected behavior

Unlock backup like in the actual ptreodactyl panel

### Actual behavior

Wont let me unlock or delete the backup

### Steps to reproduce this bug/error

Make backup but tick the lock backup option

### Possible fix

idk maybe an error in the wings

### Path/location to problematic page

https://indionicpanel.in/server/ed62fd04/backups

### Agreement

- [X] I have checked for and confirmed there isn't already a similar issue opened.
- [x] I have checked for and confirmed there isn't any browser addon/extension causing this issue.
- [X] I have tested and confirmed the presense of this bug on latest version of my preferred browser application.

**Comment by kartikay-agarwal** [comment]
The issue has been fixed and backups can now be unlocked by the user him/her self
